### Set Pin
POST http://localhost:3000/api/pin
Content-Type: application/json

{
  "pin": "123456"
}

### Verify Pin
POST http://localhost:3000/api/pin/verify
Content-Type: application/json

{
  "pin": "553388"
}

### Pin Status
GET http://localhost:3000/api/pin/status
