services:
  app:
    image: ghcr.io/javedh-dev/tracktor:dev
    container_name: tracktor-app
    restart: always
    ports:
      - "3333:3000"
    volumes:
      - ../app/backend/tracktor.db:/data/tracktor.db
    environment:
      - PUBLIC_API_BASE_URL=/

volumes:
  tracktor-app-data: null
