### Add Insurance
POST http://localhost:3000/api/vehicles/634c19aa-f2ac-4ae1-b163-7c97ab62ef4e/insurance
Content-Type: application/json
X-User-Pin: 123456

{
  "provider": "ABC Insurance",
  "policyNumber": "POL123456",
  "startDate": "2025-01-01",
  "endDate": "2026-01-01",
  "cost": 5000
}

### Get Insurance for Vehicle
GET http://localhost:3000/api/vehicles/634c19aa-f2ac-4ae1-b163-7c97ab62ef4e/insurance
X-User-Pin: 123456

### Update Insurance
PUT http://localhost:3000/api/vehicles/634c19aa-f2ac-4ae1-b163-7c97ab62ef4e/insurance
Content-Type: application/json
X-User-Pin: 123456

{
  "provider": "XYZ Insurance",
  "policyNumber": "POL654321",
  "startDate": "2025-02-01",
  "endDate": "2026-02-01",
  "cost": 5200
}

### Delete Insurance
DELETE http://localhost:3000/api/vehicles/634c19aa-f2ac-4ae1-b163-7c97ab62ef4e/insurance
X-User-Pin: 123456